-- MySQL Script generated by MySQL Workbench
-- 02/14/15 15:07:06
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema WineAdministration
-- -----------------------------------------------------
START TRANSACTION;
USE `WineAdministration` ;
-- -----------------------------------------------------
-- Data for table `WineAdministration`.`WineType`
-- -----------------------------------------------------
INSERT INTO `WineAdministration`.`WineType` (`name`) VALUES ('Weißwein');
INSERT INTO `WineAdministration`.`WineType` (`name`) VALUES ('Rotwein');
INSERT INTO `WineAdministration`.`WineType` (`name`) VALUES ('Rosé');


-- -----------------------------------------------------
-- Data for table `WineAdministration`.`City`
-- -----------------------------------------------------
INSERT INTO `WineAdministration`.`City` (`name`, `zipCode`) VALUES ('Bernkastel-Wehlen', 54470);
INSERT INTO `WineAdministration`.`City` (`name`, `zipCode`) VALUES ('La cadière d Azur', 83740 );
INSERT INTO `WineAdministration`.`City` (`name`, `zipCode`) VALUES ('Berlin', 12487);
INSERT INTO `WineAdministration`.`City` (`name`, `zipCode`) VALUES ('München', 80687);


-- -----------------------------------------------------
-- Data for table `WineAdministration`.`Client`
-- -----------------------------------------------------
INSERT INTO `WineAdministration`.`Client` (`forename`, `surname`, `street`, `streetNo`, `city`) VALUES ('Hans', 'Peter', 'Heimweg', '2', 3);
INSERT INTO `WineAdministration`.`Client` (`forename`, `surname`, `street`, `streetNo`, `city`) VALUES ('Hans', 'Ludwig', 'Hauptstr', '123', 4);
INSERT INTO `WineAdministration`.`Client` (`forename`, `surname`, `street`, `streetNo`, `city`) VALUES ('Krümel', 'Monster', 'Lapastr', '7', 3);
INSERT INTO `WineAdministration`.`Client` (`forename`, `surname`, `street`, `streetNo`, `city`) VALUES ('Steffi', 'Rull', 'Hamallee', '1', 4);


-- -----------------------------------------------------
-- Data for table `WineAdministration`.`ClientOrder`
-- -----------------------------------------------------
INSERT INTO `WineAdministration`.`ClientOrder` (`orderDate`, `client`) VALUES ('2014-01-02', 1);
INSERT INTO `WineAdministration`.`ClientOrder` (`orderDate`, `client`) VALUES ('2014-01-01', 2);


-- -----------------------------------------------------
-- Data for table `WineAdministration`.`Country`
-- -----------------------------------------------------
INSERT INTO `WineAdministration`.`Country` (`name`) VALUES ('Deutschland');
INSERT INTO `WineAdministration`.`Country` (`name`) VALUES ('Frankreich');


-- -----------------------------------------------------
-- Data for table `WineAdministration`.`WineVarietal`
-- -----------------------------------------------------
INSERT INTO `WineAdministration`.`WineVarietal` (`name`) VALUES ('Spätburgunder');
INSERT INTO `WineAdministration`.`WineVarietal` (`name`) VALUES ('Dornfelder');
INSERT INTO `WineAdministration`.`WineVarietal` (`name`) VALUES ('Barrique');
INSERT INTO `WineAdministration`.`WineVarietal` (`name`) VALUES ('Riesling');
INSERT INTO `WineAdministration`.`WineVarietal` (`name`) VALUES ('Kerner');
INSERT INTO `WineAdministration`.`WineVarietal` (`name`) VALUES ('Cuvée');


-- -----------------------------------------------------
-- Data for table `WineAdministration`.`Region`
-- -----------------------------------------------------
INSERT INTO `WineAdministration`.`Region` (`name`, `country`) VALUES ('Ahr', 1);
INSERT INTO `WineAdministration`.`Region` (`name`, `country`) VALUES ('Baden', 1);
INSERT INTO `WineAdministration`.`Region` (`name`, `country`) VALUES ('Franken', 1);
INSERT INTO `WineAdministration`.`Region` (`name`, `country`) VALUES ('Mosel', 1);
INSERT INTO `WineAdministration`.`Region` (`name`, `country`) VALUES ('Pfalz', 1);
INSERT INTO `WineAdministration`.`Region` (`name`, `country`) VALUES ('Rheingau', 1);
INSERT INTO `WineAdministration`.`Region` (`name`, `country`) VALUES ('Reinhessen', 1);
INSERT INTO `WineAdministration`.`Region` (`name`, `country`) VALUES ('Rheinland-Pfalz', 1);
INSERT INTO `WineAdministration`.`Region` (`name`, `country`) VALUES ('Württemberg', 1);
INSERT INTO `WineAdministration`.`Region` (`name`, `country`) VALUES ('Beaujolais', 2);
INSERT INTO `WineAdministration`.`Region` (`name`, `country`) VALUES ('Bordeaux', 2);
INSERT INTO `WineAdministration`.`Region` (`name`, `country`) VALUES ('Burgund', 2);
INSERT INTO `WineAdministration`.`Region` (`name`, `country`) VALUES ('Elsass', 2);
INSERT INTO `WineAdministration`.`Region` (`name`, `country`) VALUES ('Languedoc Roussillon', 2);
INSERT INTO `WineAdministration`.`Region` (`name`, `country`) VALUES ('Provence', 2);
INSERT INTO `WineAdministration`.`Region` (`name`, `country`) VALUES ('Rhône', 2);
INSERT INTO `WineAdministration`.`Region` (`name`, `country`) VALUES ('Sud-Ouest', 2);


-- -----------------------------------------------------
-- Data for table `WineAdministration`.`ClientPhone`
-- -----------------------------------------------------
INSERT INTO `WineAdministration`.`ClientPhone` (`number`, `client`) VALUES ('030-666666', 1);
INSERT INTO `WineAdministration`.`ClientPhone` (`number`, `client`) VALUES ('030-999999', 1);
INSERT INTO `WineAdministration`.`ClientPhone` (`number`, `client`) VALUES ('040-912335', 2);
INSERT INTO `WineAdministration`.`ClientPhone` (`number`, `client`) VALUES ('040-456457', 2);
INSERT INTO `WineAdministration`.`ClientPhone` (`number`, `client`) VALUES ('040-346758', 2);
INSERT INTO `WineAdministration`.`ClientPhone` (`number`, `client`) VALUES ('030-345345', 3);
INSERT INTO `WineAdministration`.`ClientPhone` (`number`, `client`) VALUES ('030-879724', 3);
INSERT INTO `WineAdministration`.`ClientPhone` (`number`, `client`) VALUES ('030-196578', 3);
INSERT INTO `WineAdministration`.`ClientPhone` (`number`, `client`) VALUES ('040-067824', 4);


-- -----------------------------------------------------
-- Data for table `WineAdministration`.`WineKind`
-- -----------------------------------------------------
INSERT INTO `WineAdministration`.`WineKind` (`name`) VALUES ('Trocken');
INSERT INTO `WineAdministration`.`WineKind` (`name`) VALUES ('Halbtrocken');
INSERT INTO `WineAdministration`.`WineKind` (`name`) VALUES ('Feinherb');
INSERT INTO `WineAdministration`.`WineKind` (`name`) VALUES ('Lieblich');


-- -----------------------------------------------------
-- Data for table `WineAdministration`.`Vineyard`
-- -----------------------------------------------------
INSERT INTO `WineAdministration`.`Vineyard` (`name`, `city`, `region`) VALUES ('Markus Molitor', 1, 4);
INSERT INTO `WineAdministration`.`Vineyard` (`name`, `city`, `region`) VALUES ('Château de Pibarnon', 2, 15);


-- -----------------------------------------------------
-- Data for table `WineAdministration`.`Wine`
-- -----------------------------------------------------
INSERT INTO `WineAdministration`.`Wine` (`available`, `price`, `name`, `vintage`, `wineType`, `vinyard`, `wineKind`, `volume`) VALUES (true, 10.9, 'Schiefersteil', '2013-01-01', 1, 1, 1, 1);
INSERT INTO `WineAdministration`.`Wine` (`available`, `price`, `name`, `vintage`, `wineType`, `vinyard`, `wineKind`, `volume`) VALUES (true, 33, 'Zeltinger Sonnenuhr', '2012-01-01', 1, 1, 4, 0.75);
INSERT INTO `WineAdministration`.`Wine` (`available`, `price`, `name`, `vintage`, `wineType`, `vinyard`, `wineKind`, `volume`) VALUES (false, 40.1, 'Rouge', '2010-01-01', 1, 2, 2, 0.75);


-- -----------------------------------------------------
-- Data for table `WineAdministration`.`WineToClientOrder`
-- -----------------------------------------------------
INSERT INTO `WineAdministration`.`WineToClientOrder` (`amount`, `price`, `wine`, `order`) VALUES (12, 45, 3, 1);
INSERT INTO `WineAdministration`.`WineToClientOrder` (`amount`, `price`, `wine`, `order`) VALUES (1, 4, 1, 2);


-- -----------------------------------------------------
-- Data for table `WineAdministration`.`WineToWineVarietal`
-- -----------------------------------------------------
INSERT INTO `WineAdministration`.`WineToWineVarietal` (`wine`, `wineVarietal`) VALUES (2, 4);
INSERT INTO `WineAdministration`.`WineToWineVarietal` (`wine`, `wineVarietal`) VALUES (3, 6);
INSERT INTO `WineAdministration`.`WineToWineVarietal` (`wine`, `wineVarietal`) VALUES (1, 4);

COMMIT;

